# Generated by Django 2.0 on 2018-04-12 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meat', '0002_auto_20180410_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_no', models.CharField(max_length=50)),
                ('pay_type', models.IntegerField(default=1)),
                ('sg_price', models.FloatField(default=0)),
                ('sg_datetime', models.DateTimeField()),
                ('cz_weight', models.FloatField(default=0)),
                ('cz_weight2', models.FloatField(default=0)),
                ('cz_weight3', models.FloatField(default=0)),
                ('cz_number', models.IntegerField(default=0)),
                ('cz_number2', models.IntegerField(default=0)),
                ('cz_number3', models.IntegerField(default=0)),
                ('standard', models.CharField(max_length=20)),
                ('c_type', models.CharField(max_length=20)),
                ('c_standard', models.CharField(max_length=20)),
                ('c_level', models.CharField(max_length=20)),
                ('state', models.IntegerField(default=1)),
                ('flow_step', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=20)),
                ('id_card', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='collectinfo',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meat.Customer'),
        ),
        migrations.AddField(
            model_name='collectinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
