# Generated by Django 2.0 on 2018-04-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0005_auto_20180412_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectinfo',
            name='standard',
        ),
    ]
